# Generated by Django 3.2.21 on 2023-10-22 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailModel',
            new_name='Email',
        ),
    ]
