# Generated by Django 3.2.21 on 2023-10-22 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20231011_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='time',
        ),
    ]
